"""Добавлены поля timezone, currency и notification_frequency

Revision ID: 407b498e0093
Revises: 
Create Date: 2024-11-20 10:28:51.457727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407b498e0093'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('period', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('type', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('threshold', sa.Integer(), nullable=True))
    op.drop_column('subscriptions', 'alert_type')
    op.drop_column('subscriptions', 'alert_value')
    op.add_column('users', sa.Column('notification_frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_frequency')
    op.add_column('subscriptions', sa.Column('alert_value', sa.INTEGER(), nullable=True))
    op.add_column('subscriptions', sa.Column('alert_type', sa.VARCHAR(), nullable=True))
    op.drop_column('subscriptions', 'threshold')
    op.drop_column('subscriptions', 'type')
    op.drop_column('subscriptions', 'active')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'period')
    # ### end Alembic commands ###
